Bugfix: Landmark float number optimization
xtravision-ai/xtravision-react pull request #21
Opened 2023-04-24 10:18 UTC by jinchuuriki91

2023-04-24 10:33 UTC, Jestin64 submitted a review, later dismissed

2023-04-25 09:40 UTC, mManishTrivedi requested changes
plz, check comment.  @jinchuuriki91

2023-04-25 09:40 UTC, mManishTrivedi commented on src/hooks/usePoseClassification.tsx
> +      console.log(l_wrist);
@jinchuuriki91  kindly remove this console.log

2023-06-09 09:02 UTC, mManishTrivedi approved these changes

2023-06-09 09:29 UTC, merged