Jestin/react sdk/meta data
xtravision-ai/xtravision-react pull request #24
Opened 2023-05-30 16:12 UTC by Jestin64

added meta data in user session to call in gql api server upon websocket onOpen connection

2023-05-30 16:27 UTC, ajayxtra requested changes
Overall looks good. Requested a few changes. Also I didn't test the code.

2023-05-30 16:27 UTC, ajayxtra commented on demo/src/pages/Workout.tsx
> +        const response = await axios.get('https://ipapi.co/json/')
I tried that URL on my laptop at office, got this data:
{
    "ip": "209.249.5.130",
    "network": "209.249.0.0/21",
    "version": "IPv4",
    "city": "Rockville Centre",
    "region": "New York",
    "region_code": "NY",
    "country": "US",
    "country_name": "United States",
    "country_code": "US",
    "country_code_iso3": "USA",
    "country_capital": "Washington",
    "country_tld": ".us",
    "continent_code": "NA",
    "in_eu": false,
    "postal": "11570",
    "latitude": 40.6598,
    "longitude": -73.6371,
    "timezone": "America/New_York",
    "utc_offset": "-0400",
    "country_calling_code": "+1",
    "currency": "USD",
    "currency_name": "Dollar",
    "languages": "en-US,es-US,haw,fr",
    "country_area": 9629091.0,
    "country_population": 327167434,
    "asn": "AS6461",
    "org": "ZAYO-6461"
}

City is not correct. So lets dump the entire json to DB.

2023-05-30 16:27 UTC, ajayxtra commented on demo/src/pages/Workout.tsx
> +          location: `${data?.city}, ${data?.region_code}, ${data?.country}`
Can we also save time zone? We should mostly get it from Moment. We may have a function in Utils to return the timezone.

2023-05-30 16:27 UTC, ajayxtra commented on demo/src/pages/Workout.tsx
> +  const [connectionDetails, setConnectionDetails] = useState() as any;
This code probably should go inside the SDK. If we add in demo app, client may skip adding this.

2023-05-30 16:27 UTC, ajayxtra commented on src/provider/constants.ts
> +export const API_SERVER_URL = "https://saasapi/api/v1/graphql"
Looks like xtravision.ai is missing from the URL.

2023-05-31 14:44 UTC, ajayxtra requested changes

2023-05-31 14:44 UTC, ajayxtra commented on src/provider/XtraVisionAssessmentProvider.tsx
> +        setConnectionDetails({
Can we save the metadata here itself instead of saving it in a state variable?

2023-05-31 14:44 UTC, ajayxtra commented on src/provider/XtraVisionAssessmentProvider.tsx
> +      try {
This block of code can be done inside "fetchData" function above.

2023-05-31 14:44 UTC, ajayxtra commented on src/provider/constants.ts
> +export const API_SERVER_URL = "http://localhost:4000/api/v1/graphql";
Don't forget to change this to prod URL.

2023-05-31 14:57 UTC, closed without merging

2023-05-31 14:57 UTC, Jestin64 commented
changing implementation, will raise new PR